FROM python:3.10-alpine

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && \
 apk update \
 && apk add  --no-cache ffmpeg \
 && rm -rf /var/cache/apk/*

COPY requirements.txt /tmp
RUN pip config set global.index-url https://pypi.douban.com/simple
RUN pip install --upgrade pip \
 && pip install -r /tmp/requirements.txt \
 && rm /tmp/requirements.txt

COPY . /root/gpt4free

WORKDIR /root/gpt4free

CMD ["streamlit", "run", "./gui/streamlit_app.py"]

EXPOSE 8501
